### ISSUE TITLE
Errors in the browser console

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#1295]
* application-2b629e248e7cb19f7e8e3673c87d7a2d3778bcb6.css:13 
        GET https://auction.internet.ee/assets/styles-6eddbe2ed74dcb6faf8d1332ac3ea35c5fe33939.scss net::ERR_ABORTED 404 (Not Found)

Many errors labeled Report Only and related to Content Security Policy directive: "connect-src 'none'". For example:
* [Report Only] Refused to load the script 'https://tara.ria.ee/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

* main.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at HTMLDocument.<anonymous> (main.js:5:558)
    at e (main.js:1:29059)
    at t (main.js:1:29385)

There are also a few warnings:
* main.js:1 jQuery.Deferred exception: Cannot read properties of undefined (reading 'getAttribute') TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at HTMLDocument.<anonymous> (https://tara.ria.ee/scripts/main.js:5:558)
    at e (https://tara.ria.ee/scripts/main.js:1:29059)
    at t (https://tara.ria.ee/scripts/main.js:1:29385) undefined
* Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
* application-6bc60bab7c756bb5c4c22bd73f42f66d88a4dafd.js:4533 The specified value "0,00" cannot be parsed, or is out of range. (when editig whishlist items)

**Comment by OlegPhenomenon** [comment]
@vohmar  Edit please ticket, because a lot of them in RIA side
